### ISSUE TITLE
[BUG] No character sheet is visible

### ISSUE THREAD

**Issue by Pandry** [Syrious/foundryvtt-sheet-only#22]
Hello!!

First and foremost thank you for the great work: I've been looking for a plugin like this for a long time.  
Unfortunately, I'm having a bit of issues making it work in my current setup, as you can see from the screenshot:

![image](https://github.com/Syrious/foundryvtt-sheet-only/assets/17499836/f61e4ffa-d85a-4d6d-9f87-58b01f3517df)

I'm not seeing any HTML element where I suppose the character sheet would need to appear.  
The user I'm using has owner permission on 1 character sheet. I can see and edit the sheet by disabling the module for the user.

Foundry build: 11.315 (running on Docker, I'm not sure if this could be somehow a problem)
Game system: D&D 3.1.1
Active modules: Sheet only v1.1.3
Browsers: Firefox 124/Safari 17/Chromium 118

Browser console doesn't show anything I could see as relevant but this error:

```
Uncaught (in promise) Error: This is not a registered game setting
    get https://foundry/scripts/foundry.js:3339
    realDice https://foundrymodules/sheet-only/scripts/compatibility.js:16
    setupCompatibility https://foundry/modules/sheet-only/scripts/compatibility.js:2
    <anonymous> https://foundry/modules/sheet-only/scripts/main.js:27
    #call https://foundry/scripts/foundry.js:730
    callAll https://foundry/scripts/foundry.js:687
    setupGame https://foundry/scripts/foundry.js:8712
    _initializeGameView https://foundry/scripts/foundry.js:9990
    _initializeView https://foundry/scripts/foundry.js:9966
    initialize https://foundry/scripts/foundry.js:8650
    async* https://foundry/scripts/foundry.js:91833
    async* https://foundry/scripts/foundry.js:91809
[foundry.js:3339:42](https://foundry/scripts/foundry.js)
```

Installing RealDice (and thus bringing the active modules to: Sheet only - v1.1.3; libWrapper v1.12.13.0; RealDice v1.1.3) actually made the console error disappear, but the problem still remains

I feel I'm missing something, what could it be?

---

EDIT

Actually, while debugging, I found [this line](https://github.com/Syrious/foundryvtt-sheet-only/blob/main/scripts/main.js#L231) and going backwards I could actually see `No actor for user found.` beging printed in the logs   
This seems to be due of `game.user.character` [in the `popupSheet`](https://github.com/Syrious/foundryvtt-sheet-only/blob/da385c366a532870250380fdd9be64185657cd8b/scripts/main.js#L223C4-L223C34) being null

The [function `getOwnedActors()`](https://github.com/Syrious/foundryvtt-sheet-only/blob/da385c366a532870250380fdd9be64185657cd8b/scripts/main.js#L123C10-L123C24) seems to work properly

I (very much) hacked around a fix

```diff
   function popupSheet(user) {
-      const actor = user.character;
+     const actor = user.character??getOwnedActors()[0]??null;
       currentActor = actor;
```

**Comment by Syrious** [comment]
Hi.

That seems weird. What other modules do you have installed?
I just created a new world with only the following modules activated:

- Sheet-Only
- RealDice
- libWrapper 

I had no issues with that so I assume some other module might interfere.

**Comment by Pandry** [comment]
I disabled all the modules but this, to avoid interference from other modules

**Comment by Pandry** [comment]
Just tried it out with DnD5e and I can confirm the issue is still present :c

**Comment by Syrious** [comment]
That is very odd.

What docker image do you use?

**Comment by Pandry** [comment]
Right now, the image `felddy/foundryvtt:11.315.1`

**Comment by Syrious** [comment]
I use the exact same image.
I just create a whole now instance, added only the three modules and it worked. Here is the step by step, just in case you missed one:

1. Activate modules: Sheet-Only, Real-Dice, libWrapper
2. Create a user
3. got to settings -> sheet-only -> User Select and select the added user
4. Create an actor and add the player as owner (not "All players") 
<img width="295" alt="image" src="https://github.com/Syrious/foundryvtt-sheet-only/assets/8050391/55f72d04-ee03-42d3-b6dd-2c5d5f0f69b5">

5. Start a new browser tab and log in with the player
6. Chose the character that is represented by the play

After hitting the button, the sheet should be visible.

And just in case that did not work either: Here's my world I just tested it on. Extract the content into your data/Backups/worlds folder so that the full path would be `data/Backups/worlds/sheet-only-test` with the .bak and .json as content

[sheet-only-test.zip](https://github.com/Syrious/foundryvtt-sheet-only/files/14970068/sheet-only-test.zip)

And even it should not matter: What browser are you working with?

**Comment by Syrious** [comment]
Hey there,

try the new version 1.1.7. I changed some code so the module will check periodically, if an actor owned by the user exists

**Comment by Pandry** [comment]
Hi  
I'm extremely sorry for the huge delay.  
---
So, I've tested your backup world and I can confirm it works.  
Extremely fun fact: I've tested again both my world and both are still not working (again, only `Sheet only - v1.1.3; libWrapper v1.12.13.0; RealDice v1.1.3` extensions)  
---
Finally, I've tested with the version 1.1.7 that it's now working with all 3 of my worlds!  
Thank you so much!

**Comment by Syrious** [comment]
No worries, 

I think the issue is that Foundry seems not wait before starting the next step in its life cycle. That means it calls the "Ready"-Hook before everything from the "Setup"-Hook has been processed. If Foundry then has many things to initialize the actor might not be there when Sheet-Only tries to find them. These race-conditions are really hard to reproduce and I am glad that it works now :)
