### ISSUE TITLE
Rolling initiative from Sheet Only adds a copy of character to tracker

### ISSUE THREAD

**Issue by jesjhoward** [Syrious/foundryvtt-sheet-only#23]
Firstly, THANK YOU for this module. Been a big fan of it so far. Looking forward to joining your paid teir for targeting and using it for local groups.

I've noticed that when the GM adds actors to the combat tracker, and a player rolls initiative from the module, two rolls happen for that actor and a copy of them is added to the tracker. I have removed every other module I had installed, but the same thing happens

**Comment by Syrious** [comment]
Hi.

Thanks for your kind words :)

Could you provide me with the following data?

- FoundryVTT version
- Game system and version
- Which Sheet-Only version
- A step-by-step example on how to reproduce the behavior

**Comment by Syrious** [comment]
Hi again.

I already looked into it and can confirm the issue.

<img width="412" alt="image" src="https://github.com/Syrious/foundryvtt-sheet-only/assets/8050391/137ea67a-c24a-42bb-91f9-f5db1cc9d584">

Try to uncheck the "Disable Canvas" option and see if this solves your problem.

**Comment by jesjhoward** [comment]
That does indeed solve the issue. My plan is to run this on something like laptops or tablets for my players. Will this cause a significant slowdown over time, do you think?

**Comment by Syrious** [comment]
I think, most devices should be fine with it, since the sheet-only hides all visuals from the canvas, but not disabling its features.

If your players are having issues disable sheet-only for them shortly. Let them check their foundry settings. 
I would recommend the following core-settings:
 
- Disable Pixel Ratio Resolution Scaling
- Set Performance Mode to Low
- Set maximum Framerate to 10
- Disable Token Drag Vision
- Disable Token Vision Animation
- Disable Light Source Animation
- Disable Zoomed Texture Antialiasing
 
<img width="669" alt="image" src="https://github.com/Syrious/foundryvtt-sheet-only/assets/8050391/9ce389c8-d8d8-49b1-ba59-f7685f4ade9e">

<img width="667" alt="image" src="https://github.com/Syrious/foundryvtt-sheet-only/assets/8050391/e452ded2-2cc7-4d73-8b56-019c5914209d">

As a side note: Since targeting (Sheet-Only-Plus) is not possible without the canvas you would have it enabled anyway when using the plus features.

**Comment by jesjhoward** [comment]
Gotcha. Thanks a bunch!

**Comment by Syrious** [comment]
You're welcome and let me know if another issue occurs :)
