### ISSUE TITLE
[BUG] Hide Canvas / Data Sync / Perfomance

### ISSUE THREAD

**Issue by McMuffin88** [Syrious/foundryvtt-sheet-only#27]
####
Issue description: Even when the canvas is not supposed to load, it still does. Additionally, the tablet receives an error message about a data sync difference. This message keeps recurring and leads to continuous reloading if the sync is chosen as 'yes'. If 'no' is selected, the entire system becomes inefficient and the canvas still loads (visible in horizontal mode).

#### 
Expected behavior:
When 'hide canvas' is selected, the play area should be permanently disabled, which should actually improve performance. As soon as the play area is not disabled, everything is fast and fluid.

#### System & versions
System Dungeons & Dragons Fifth Edition
Version 11 Build 315

#### 
Step to reproduce:
Select 'Hide Canvas' and reload the page. The following information appears in the attached image and/or the performance deteriorates.

![1713820519817](https://github.com/Syrious/foundryvtt-sheet-only/assets/75749644/3a0cbed9-285b-4aa2-a1ea-b652b636ecff)

**Comment by Syrious** [comment]
Hi,

since sheet-only version 1.1.4 the canvas must be enabled (but it is hidden). Otherwise a lot of things would break, like targeting. Since is a restriction by foundry. Without a canvas, there are no tokens. And without tokens there can't be anything targeted.

The saved setting (I think it comes from a Monk's module) probably saved a state of an older version. Please select false for that.

**Comment by ThePlanplan** [comment]
Although this is not a bug, the module becomes less appealing if the canvas is required because of its poor performance on tablets or phones. It exacerbates the issue of the sheets already a little sluggish and unresponsive on these devices.

I understand why you work on those target and move options, but I'm using your module for "sheet only" (yeah :grin:).

Perhaps the canvas should only be hidden when using targeting or moving, and disabled otherwise? Or a DM setting to disable certain players canvas ?

**Comment by Niclasp1501** [comment]
I agree: The 'Sheet-Only' module worked quite well without Canvas. Now the Canvas is always activated, which severely impacts the performance on tablets. Maps have to be constantly downloaded, which causes significant traffic with five players and one monitor, and also consumes more power. Moreover, I don't need the functionality for tokens to move or for targeting. A pure 'Sheet-Only' function with improved access to authorized character sheets and the ability to grant players access to the journals would indeed be legendary. ❤️

**Comment by Syrious** [comment]
I see your point. I will change it so that all the extra stuff (even with sheet-only-plus installed) will be modular and optional. Only those who want to use targeting have to enable the canvas. 

The access to the journal is requested quite often and I'm already working on it but it still needs some time. But it will come :)

**Comment by Syrious** [comment]
Hey guys,

So, in version 1.1.7 each client can choose whether or not to disable canvas. It is disabled by default and needs to be enabled to use certain features.
