### ISSUE TITLE
[IMPROVEMENT] Open Dokuments

### ISSUE THREAD

**Issue by McMuffin88** [Syrious/foundryvtt-sheet-only#29]
Is your feature request related to a problem? Please describe.

Currently, there is no convenient way for players to access notes directly from the character sheet to review quests or documents. This limitation can interrupt gameplay and reduce immersion.

Describe the solution you'd like

It would be great if there were an option to open notes directly within the sheet, allowing players to easily access quest details or documents. Ideally, this could be facilitated by a button located at the bottom right, similar to the chat button.

Describe alternatives you've considered

An alternative solution could be to integrate a sidebar with a notes tab that can be expanded and collapsed as needed. This would still provide quick access to notes without permanently occupying screen space.

### Additional context
I would be really pleased if this implementation could be achieved, as this is a major downside of the module for me. I don't want to have to ask the Dungeon Master every time I want to look something up on my own. Perhaps there is an easy way to retrofit this feature?

Thanks a lot :)

**Comment by Syrious** [comment]
Hey there,

this feature is already in the making. But it still need quite some work. I' keep you posted :)

**Comment by Syrious** [comment]
The journal access has been integrated in the newest version of sheet-only-plus

**Comment by Niclasp1501** [comment]
@Syrious 
Last weekend, I sat down intending to support you with the implementation of the Journal function. I designed a proof of concept (PoC) that was based on your Chat-Log function and worked similarly. Only a few minor adjustments and some CSS code were necessary. I planned to push it to a separate branch of yours today or in the next few days. However, I noticed today that you have already implemented this function. It seems I was a bit too slow.

Unfortunately, I then saw that this is a premium feature, and I must admit, I'm somewhat disappointed. You've designed an excellent module, and I believe many, including myself, would be willing to support you both in coding and financially. However, subscribing to a Patreon for a module doesn't seem quite right to me. It's a real pity.

I think your module could truly be a hit. Perhaps you might reconsider your business model to initially gain more reach and support, benefiting financially from donations or other models. Alternatively, I find hiding basic features behind a Patreon paywall to be rather unappealing.

**Comment by Syrious** [comment]
Hello @Niclasp1501,

I understand your point and your disappointment. I initially intended for the journal to be an add-on for the base version of Sheet-Only. It started out simple, but I got carried away from the initial idea and added more features until people started complaining. And they were right. Sheet-Only should be exactly what it says on the box: Only the sheet. While I really enjoy working on my modules and creating new ones, it is still a lot of work and I spend many hours of my free time on it. I do not have a business model; it's just me doing this after work.

For just 3€, you're getting access to hundreds of hours of work that I've put into this and other modules. You can easily cancel your subscription after downloading. I would recommend locking both Sheet-Only-Plus and Sheet-Only so that the latter does not get updated accidentally. I'm also considering downgrading sheet-only-plus from premium to for free after some time in the future.

I hope you can empathize with my situation and understand where I'm coming from. Your understanding is greatly appreciated.

Thank you ❤️,
Syrious

**Comment by Niclasp1501** [comment]
Hey @Syrious, 
thank you so much for your understanding response. Please don’t get me wrong, I really appreciate your work and wanted to support you by contributing the Journal as a PoC. However, I'm not a great web developer myself, so your solution is probably better. To support you a bit, I will subscribe via Patreon.

Just a quick note, the description of the Plus features doesn't make it clear that one only needs to subscribe once to get the Plus features. If you clarify in your description that it’s only 3€, and one needs to resubscribe only for new features, I’m sure more people would do it. Alternatively, there are also options like PayPal donations or Buy Me a Coffee for voluntary support. Thank you for this constructive dialogue.

**Comment by Syrious** [comment]
Hey @Niclasp1501,

thanks for your kind words and your patronage. Adding that additional hints to the readme is a great idea. Thanks for that. I'll add it soon :)
