### ISSUE TITLE
[BUG] Sheet Only endless loop with Force Client Settings and libWrapper active

### ISSUE THREAD

**Issue by gambit07** [Syrious/foundryvtt-sheet-only#45]
## Before raising an issue
- Update the game system and all modules to the current version
- Disable all other modules and see if the issue goes away
  - If this is the case, please use [Find The Culprit](<https://foundryvtt.com/packages/find-the-culprit/>) to narrow down the suspects
- Disable Sheet-Only, log into Foundry with your desired device and open a character sheet manually. If this does not work without issues then your device might not be compatible with FoundryVTT 
- If the issue persists, please go ahead and fill out the issue template

#### Issue description
An interaction between Sheet Only, Force Client Settings, and libWrapper causes an endless refresh when trying to login to a player sheet.

#### Expected behavior
The players sheet would be displayed

#### System & versions
Foundry: 11.315
5e: 3.1.2
Sheet Only: 1.3.0
Force Client Settings: 2.4.1
libWrapper: 1.12.13.0

Module-Version: ...
1.3.0

#### Steps to reproduce the issue
Please give me a short step-by-step instruction to reproduce the issue

1. Install and activate FTC, Sheet Only, and libWrapper
2. Login as a player with Sheet Only enabled

**Comment by Syrious** [comment]
Hey there,

and thanks for reporting the issue. Unfortunately I can not reproduce the issue. 

1. Created a new world with the game system, modules and respective versions
2. I created a new player and gave them an actor 
3. I enabled all modules
4. I set the newly created player as Sheet-Only user in Sheet-Only settings
5. I logged in with the user, using a different browser (since most settings are stored inside the browser, it is advised to not use the same browser instance for multiple users. Instead open a new profile (like in brave browser) or use one incognito instance)
6. The sheet loads without issue

I think the crucial part is the settings you are enforcing upon your clients. Could you share more details in what way you are using Force Client Settings? My strongest guess is that you the following combination of settings and enforcement:

- Sheet-Only: Canvas Control is set to 'Disable'
- Force Client Settings: Is forcing core -> Disable-Canvas to be unchecked

Force Client Settings enables the canvas but sheet-only disables it and reloads. Then Force Client Settings enables it again and so forth, resulting in a reload loop.
Please try to set Sheet-Only Canvas Control to "No Control" or disable FCS to enforce canvas settings.

**Comment by gambit07** [comment]
> Hey there,
> 
> and thanks for reporting the issue. Unfortunately I can not reproduce the issue.
> 
>     1. Created a new world with the game system, modules and respective versions
> 
>     2. I created a new player and gave them an actor
> 
>     3. I enabled all modules
> 
>     4. I set the newly created player as Sheet-Only user in Sheet-Only settings
> 
>     5. I logged in with the user, using a different browser (since most settings are stored inside the browser, it is advised to not use the same browser instance for multiple users. Instead open a new profile (like in brave browser) or use one incognito instance)
> 
>     6. The sheet loads without issue
> 
> 
> I think the crucial part is the settings you are enforcing upon your clients. Could you share more details in what way you are using Force Client Settings? My strongest guess is the following combination of settings and enforcements:
> 
>     * Sheet-Only: Canvas Control is set to 'Disable'
> 
>     * Force Client Settings: Is forcing core -> Disable-Canvas to be unchecked
> 
> 
> Force Client Settings enables the canvas but sheet-only disables it and reloads. Then Force Client Settings enables it again and so forth, resulting in a reload loop. Please try to set Sheet-Only Canvas Control to "No Control" or disable FCS to enforce canvas settings.

Thanks for the detailed response! You were right, it was the core canvas setting being locked. I'm not sure why testing with FTC + Sheet Only wasn't enough to trigger that, but it is resolved now :) Thanks!

**Comment by gambit07** [comment]
Seems like having FTC set to Soft lock also causes the endless refresh to occur, so that core field needs to be completely unlocked with FTC to work correctly. I also had an issue where I was testing on a desktop browser with no activation screen width set. Once that worked I set a screen width up and the browser instance booted up with Disable Canvas still set as enabled, even though Sheet Only did not open the character sheet (as expected).

Anyway those might be one offs so I'll try to do some additional tests. Great work on this module! Really helpful for players who miss being able to log into something like dndbeyond to see their character info

**Comment by Syrious** [comment]
> I also had an issue where I was testing on a desktop browser with no activation screen width set. Once that worked I set a screen width up and the browser instance booted up with Disable Canvas still set as enabled, even though Sheet Only did not open the character sheet (as expected).

When the sheet-only ode is not triggered it does not (and cannot) touch the canvas settings. So, if the canvas is disabled (by whoever) sheet-only only enables it when needed for targeting or token movement (both Sheet-Only-Plus features). If sheet-only gets deactivated it does not trigger enabling the canvas, since it can not know if there is any other module present, making changes to the canvas. The user has to enable it manually.

To avoid confusion: The "Activation Screen Width" is a minimum settings. Sheet-Only will only activate if the screen width is smaller than the given value

On another note: You might want to check out [Module Management+](https://foundryvtt.com/packages/module-credits). This also enables you to manually send settings to the clients and lock some settings for clients

**Comment by gambit07** [comment]
> > I also had an issue where I was testing on a desktop browser with no activation screen width set. Once that worked I set a screen width up and the browser instance booted up with Disable Canvas still set as enabled, even though Sheet Only did not open the character sheet (as expected).
> 
> When the sheet-only ode is not triggered it does not (and cannot) touch the canvas settings. So, if the canvas is disabled (by whoever) sheet-only only enables it when needed for targeting or token movement (both Sheet-Only-Plus features). If sheet-only gets deactivated it does not trigger enabling the canvas, since it can not know if there is any other module present, making changes to the canvas. The user has to enable it manually.
> 
> To avoid confusion: The "Activation Screen Width" is a minimum settings. Sheet-Only will only activate if the screen width is smaller than the given value
> 
> On another note: You might want to check out [Module Management+](https://foundryvtt.com/packages/module-credits). This also enables you to manually send settings to clients and lock some settings for clients

Thanks for the info! The activation screen width setting works great and yeah I was testing it as a minimum setting

So to ensure Sheet Only works while also maintaining the state of the game canvas currently, I should change SO to a mode that does not disable the canvas while leaving FTC's core canvas setting unlocked? 

Since a player is not manually disabling the canvas core option when Sheet Only activates and the SO disable option is set, I think they would be pretty confused when they login for a desktop game and don't see the canvas.

Would it be possible to store the state of that disable canvas core setting prior to a minimum width being recognized, and potentially re-activate the core canvas setting when that minimum width is no longer recognized and the previous state was canvas enabled?

**Comment by Syrious** [comment]
> So to ensure Sheet Only works while also maintaining the state of the game canvas currently, I should change SO to a mode that does not disable the canvas while leaving FTC's core canvas setting unlocked?

You can set SO's Canvas Control settings to "No Control". That way SO does nothing to the canvas. Another option would be "Hide". This just makes the canvas invisible but it is still there.

> Since a player is not manually disabling the canvas core option when Sheet Only activates and the SO disable option is set, I think they would be pretty confused when they login for a desktop game and don't see the canvas.

The weird thing is, that Foundry does not store the settings on the user but on the browser. Meaning, if a player has SO running on a tablet with canvas disabled, and they use a desktop browser, there the canvas is still enabled

> Would it be possible to store the state of that disable canvas core setting prior to a minimum width being recognized, and potentially re-activate the core canvas setting when that minimum width is no longer recognized and the previous state was canvas enabled?

It would be possible but not advisable. Here we would have the same situation that brought you here. In this case, if another module tries to disable the canvas sheet-only enables it again (it's a matter of whose code runs first) ending in end endless loop.

**Comment by gambit07** [comment]
Makes sense, thanks for the feedback!

**Comment by Syrious** [comment]
Edit: But I can prompt the user if they want to enable the canvas ;) Working on it
